name: 'Semver Github Action'
description: 'Get version from latest tag, bump it and create new tag'
branding:
  icon: tag
  color: orange
4 inputs:
5   pre_release:
6     description: 'indicates if this is a pre-release build'
7     required: false
8     default: false
outputs:
  tag:
    description: 'Current tag'
  version:
    description: 'Current version'
  new_tag:
    description: 'New tag'
  new_version:
    description: 'New version'
runs:
  using: 'docker'
  image: 'Dockerfile'