name: 'Semver Github Action'
description: 'Get version from latest tag, bump it and create new tag'
branding:
  icon: tag
  color: orange
outputs:
  old_tag:
    description: 'Old tag'
  old_version:
    description: 'Old version'
  new_tag:
    description: 'New tag'
  new_version:
    description: 'New version'
runs:
  using: 'docker'
  image: 'Dockerfile'